spring.application.name=secondProjectUsingDTO-Validation

spring.datasource.url=jdbc:mysql://localhost:3306/collage
spring.datasource.username=root
spring.datasource.password=Saurabh@2810

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
