spring.application.name=springBootCrud
spring.datasource.url=jdbc:mysql://localhost:3306/student
spring.datasource.username=root
spring.datasource.password=Saurabh@2810

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql = true





#
#spring.datasource.url=jdbc:mysql://localhost:3306/student_db --> yaha db url
#spring.datasource.username=root -->user name
#spring.datasource.password=YOUR_PASSWORD --> yaha password
#
#spring.jpa.hibernate.ddl-auto=update ---> agar hamne database me koii v table create nhi kia hai to update likhenge taki
# taki hmara spring jpa entity ke hisab se table create kr de ..... agar hamne menualy table create kr lia haii
# to none use karenge but table entity se match hona chahiye
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect --> yah btati haii ki hibernate ki database ke hisab se query likhegi