spring.application.name=demoApplication
paymentGateway.type=paytm
paymentGateway.count =5
payment-property.type=UPI
payment-property.retryCount=8
payment-property.enabled =true
payment-property.timeout = 3000


